resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: aoldershaw/github-pr-resource

resources:
- name: pull-requests
  type: pull-request
  check_every: 5m
  webhook_token: ((pr-webhook-token))
  source:
    repository: husseinnahle/MGL869
    access_token: ((github-access-token))

- name: repo
  type: git
  source:
    uri: https://github.com/husseinnahle/MGL869
    branch: main

jobs:
- name: test
  plan:
  - get: repo
  - get: pull-requests
    trigger: true
  - load_var: pull_requests
    file: pull-requests/prs.json
  - across:
    - var: pr
      values: ((.:pull_requests))
    set_pipeline: prs
    file: repo/ci/template.yml
    instance_vars: {number: ((.:pr.number))}
    vars: {github-access-token: ((github-access-token)), pr-webhook-token: ((pr-webhook-token)), artifactory-host: ((artifactory-host)), artifactory-password: ((artifactory-password))}